# Generated by Django 3.2.8 on 2023-04-11 17:37

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20220728_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AddField(
            model_name='certificate',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration in hours'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, upload_to=user_profile.models.certificate_file_path, verbose_name='Certificate file'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(max_length=100, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=user_profile.models.profile_picture_file_path, verbose_name='Profile picture'),
        ),
    ]
