# Generated by Django 3.2.5 on 2021-08-08 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='Name')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('picture', models.ImageField(blank=True, upload_to='images/profiles', verbose_name='Profile picture')),
                ('birthday', models.DateField(blank=True, verbose_name='Birthday')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='Location')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact email')),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('website', models.URLField(blank=True, max_length=256, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Software tool'), (1, 'Programing Language'), (2, 'Software framework'), (3, 'Architecture / Paradigm')], null=True, verbose_name='Skill type')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'Beginner'), (1, 'Elementary'), (2, 'Intermediate'), (3, 'Advance'), (4, 'Proficient')], verbose_name='Proficiency level')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.profile', verbose_name='User profile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.skill', verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'userskill',
                'verbose_name_plural': 'userskills',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network', models.IntegerField(choices=[(0, 'GitHub'), (1, 'LinkedIn')], verbose_name='Social Network')),
                ('link', models.URLField(verbose_name='Link')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.profile', verbose_name='User profile')),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Socials',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='skill_set',
            field=models.ManyToManyField(blank=True, to='resume.Skill', verbose_name='skills'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='PortfolioEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cover', models.ImageField(blank=True, upload_to='images/portfolio', verbose_name='Cover image')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('date', models.DateField(blank=True, verbose_name='Date')),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Side project'), (1, 'Client project'), (2, 'Product'), (3, 'Publication')], null=True, verbose_name='Entry type')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.profile', verbose_name='User profile')),
            ],
            options={
                'verbose_name': 'portfolio entry',
                'verbose_name_plural': 'portfolio entries',
            },
        ),
        migrations.CreateModel(
            name='JobExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='Location')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('company', models.CharField(max_length=50, verbose_name='Company')),
                ('role', models.CharField(max_length=50, verbose_name='Role')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.profile', verbose_name='User profile')),
            ],
            options={
                'verbose_name': 'Job experience',
                'verbose_name_plural': 'Job experiences',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('link', models.URLField(blank=True, verbose_name='Certificate link')),
                ('file', models.FileField(blank=True, upload_to='storage/portfolio', verbose_name='Certificate file')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.profile', verbose_name='User profile')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.skill', verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
            },
        ),
        migrations.CreateModel(
            name='AcademicExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='Location')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('school', models.CharField(max_length=50, verbose_name='School')),
                ('course', models.CharField(max_length=50, verbose_name='Course')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.profile', verbose_name='User profile')),
            ],
            options={
                'verbose_name': 'Academic experience',
                'verbose_name_plural': 'Academic experiences',
            },
        ),
    ]
