# Generated by Django 3.2.8 on 2021-12-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicexperience',
            options={'ordering': ['-start_date'], 'verbose_name': 'Academic experience', 'verbose_name_plural': 'Academic experiences'},
        ),
        migrations.AlterModelOptions(
            name='jobexperience',
            options={'ordering': ['-start_date'], 'verbose_name': 'Job experience', 'verbose_name_plural': 'Job experiences'},
        ),
    ]
