# Generated by Django 3.2.5 on 2021-08-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Social media', 'verbose_name_plural': 'Social medias'},
        ),
        migrations.AlterModelOptions(
            name='userskill',
            options={'verbose_name': "users' skill", 'verbose_name_plural': "users' skills"},
        ),
        migrations.AlterModelOptions(
            name='usersociallink',
            options={'verbose_name': "User's social media link", 'verbose_name_plural': "User's social media links"},
        ),
        migrations.AddField(
            model_name='profile',
            name='summary_en',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='profile',
            name='summary_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='profile',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='profile',
            name='title_pt_br',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
    ]
