# Generated by Django 3.2.5 on 2021-08-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210812_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicexperience',
            name='course_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='academicexperience',
            name='course_pt_br',
            field=models.CharField(max_length=50, null=True, verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='academicexperience',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='academicexperience',
            name='description_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='name_pt_br',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='description_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='role_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='role_pt_br',
            field=models.CharField(max_length=50, null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='portfolioentry',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='portfolioentry',
            name='description_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='portfolioentry',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='portfolioentry',
            name='title_pt_br',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_pt_br',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Software'), (1, 'Programing language'), (2, 'Programing tool'), (3, 'Software framework'), (4, 'Architecture / Paradigm'), (5, 'Language'), (6, 'Soft skill')], null=True, verbose_name='Skill type'),
        ),
    ]
