# Generated by Django 3.2.8 on 2021-12-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20211226_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexperience',
            name='skills_applied',
            field=models.ManyToManyField(blank=True, to='resume.UserSkill', verbose_name='Skills applied'),
        ),
    ]
